const ACTION_TYPES = {
    ADD_NEW_MEMO: "ADD_NEW_MEMO",
    SELECT_MEMO: "SELECT_MEMO",
    EDIT_MEMO: "EDIT_MEMO",
    SAVE_MEMO: "SAVE_MEMO",
    DELETE_MEMO: "DELETE_MEMO",
    FETCH_MEMOS_PENDING: "FETCH_MEMOS_PENDING",
    FETCH_MEMOS_SUCCESS: "FETCH_MEMOS_SUCCESS",
    FETCH_MEMOS_ERROR: "FETCH_MEMOS_ERROR",
    SAVE_MEMO_PENDING: "SAVE_MEMO_PENDING",
    SAVE_MEMO_SUCCESS: "SAVE_MEMO_SUCCESS",
    SAVE_MEMO_ERROR: "SAVE_MEMO_ERROR",
    ADD_MEMO_PENDING: "ADD_MEMO_PENDING",
    ADD_MEMO_SUCCESS: "ADD_MEMO_SUCCESS",
    ADD_MEMO_ERROR: "ADD_MEMO_ERROR",
    SHOW_EDIT_MEMO_POPUP: "SHOW_EDIT_MEMO_POPUP",
    SHOW_ADD_MEMO_POPUP: "SHOW_ADD_MEMO_POPUP",
    CLOSE_EDIT_POPUP: "CLOSE_EDIT_POPUP",
    DELETE_MEMO_PENDING: "DELETE_MEMO_PENDING",
    DELETE_MEMO_SUCCESS: "DELETE_MEMO_SUCCESS",
    DELETE_MEMO_ERROR: "DELETE_MEMO_ERROR",
    SET_LOGIN_PENDING: "SET_LOGIN_PENDING",
    SET_LOGIN_SUCCESS: "SET_LOGIN_SUCCESS",
    SET_LOGIN_ERROR: "SET_LOGIN_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    LOGOUT: "LOGOUT"
};

let actionTypes = ACTION_TYPES

export default actionTypes;